### ISSUE TITLE
Добавить Swagger и Redoc для документирования API

### ISSUE THREAD

**Issue by AlexandrYZ** [RDavydenko/ReportServiceAPI#1]
В результате будет доступна страница для просмотра всех имеющихся ресурсов и методов для работы.

Redoc должен открываться по адресу /

Ссылки
1. [Swashbuckle](https://docs.microsoft.com/ru-ru/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-3.1&tabs=visual-studio)
2. [Redoc](https://github.com/Redocly/redoc)

**Comment by RDavydenko** [comment]
Добавил
